# **Assignment For Numpy**

# Name : Muhammad Usman Khan

# Roll No. : PIAIC79201

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
np.shape(arr)

(40,)

5. Print the type of the previous array in question 3

In [9]:
type(arr)

numpy.ndarray

6. Print the numpy version and the configuration


In [10]:
print("Version: ",np.__version__)
print("Configuration: ",np.show_config())

Version:  1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mohammad Usman Khan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mohammad Usman Khan/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mohammad Usman Khan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\co

7. Print the dimension of the array in question 3


In [12]:
 np.ndim(arr)

1

8. Create a boolean array with all the True values

In [13]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [16]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [18]:
arr3d=np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
vector=np.arange(10)
print("Vector: ",vector)
reverse_vector=vector[::-1]
print("Reverse_Vector: ",reverse_vector)

Vector:  [0 1 2 3 4 5 6 7 8 9]
Reverse_Vector:  [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [29]:
a=np.zeros(10)
print(a)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [42]:
arr=np.array([1,2,3,4,5], dtype=np.float)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [2]:
arr1=np.array([[1.,2.,3.], [4.,5.,6.]])
arr2=np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr1 * arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [3]:
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [11]:
arr=np.arange(10)
odd_arr=arr[arr % 2==1]
odd_arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [14]:
odd_arr[0:]=-1
odd_arr

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [16]:
arr=np.arange(10)
print("Original Array: ",arr)
arr[5:9]=12
print("Replaces by 12: ",arr)

Original Array:  [0 1 2 3 4 5 6 7 8 9]
Replaces by 12:  [ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [22]:
arr2d=np.ones((5,5))
print("Original Arry")
print(arr2d,"\n")
arr2d[1:4,1:4]=0
print("Changed Array")
print(arr2d)

Original Arry
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Changed Array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [26]:
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array: ")
print(arr2d,"\n")
arr2d[1][1]=12
print("Changed Array: ")
print(arr2d)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Changed Array: 
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [9]:
arr3d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original Arrray")
print(arr3d)
arr3d[0][0]=64
print("\nChanged Array")
print(arr3d)

Original Arrray
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Changed Array
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [37]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,"\n")
arr1=arr[0:1, 0:5].ravel()
print("1d Array")
print(arr1)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]] 

1d Array
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [45]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,'\n')
arr1=arr[1:2, 0:5].ravel()
print("slice out the 2nd value from 2nd 1-D array")
arr1[1]

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]] 

slice out the 2nd value from 2nd 1-D array


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [49]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,'\n')
arr1=arr[0:2, 3:4]
print("Third column but only the first two rows")
print(arr1)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]] 

Third column but only the first two rows
[[3]
 [8]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [53]:
arr=np.random.randn(10,10)
print("Original Array")
print(arr,'\n')
maximum=np.amax(arr)
print("Maximum Value")
print(maximum,'\n')
minimum=np.amin(arr)
print("Minimum Value")
print(minimum)

Original Array
[[ 2.02471764 -0.14614099  1.33103406 -0.74273953  0.11914165  1.16118574
   0.62229472 -0.78508152  0.54625138  0.49903472]
 [-1.23087236 -1.3504192   0.8930029  -2.24617138  1.1488447  -0.46926167
  -0.95414262  1.57083683  1.02624625  0.29639535]
 [-0.81048071  0.13511366  1.4798221   0.55313823  0.10444071  0.25589098
  -0.82999483 -0.06103305 -0.11241222 -1.33762014]
 [ 0.1835389  -0.56904057 -0.28597002  0.36992848  1.97543963 -1.39069556
   0.42144136 -0.42896092  1.03394612 -1.6444519 ]
 [ 1.41685912 -0.39019459 -1.64715431  0.68517268 -0.06540343  0.57431042
   0.68192338 -1.26945123 -0.81525588  0.07763044]
 [ 1.65916802  0.34218327 -1.99404594 -1.80199229 -0.40210315  0.84794228
  -0.43343425 -0.63267478  0.10128998  1.06678425]
 [-0.12825442  0.34987518  0.32198575 -0.65701533 -0.68626815  0.36122037
   1.1063359  -1.39005941  0.28672025 -0.55027563]
 [-1.47327631  0.03436534 -0.05614839 -0.20451395 -0.65823353 -0.58790373
   0.38254777 -0.13227362 -0.6776065

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [54]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b,'\n')
print("Common Items Between a and b")
print(a==b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8] 

Common Items Between a and b
[False  True False  True False  True False  True False False]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [57]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(np.in1d(a, b))[0]
c

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.04957523, -0.75688379, -0.51893227, -0.13840716],
       [-0.34209692, -0.10789075, -0.57691646, -0.0117872 ],
       [-0.07410157,  0.41052451,  0.77179619,  0.86869432],
       [ 0.5317643 , -0.81480746,  1.31323616, -0.23036212],
       [ 0.32511977,  1.54612609, -1.54718784,  0.59059078]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names!='Joe'],'\n')
print(data[names!='will'])

[[-0.84622744 -1.11263894  0.70887697 -1.48845508]
 [ 0.92318246 -0.44147661 -0.571271   -0.69638513]
 [-0.48188231 -0.4448002   0.45485325  1.51766834]
 [ 0.32058434 -1.85472708  1.91265706 -0.98197215]] 

[[-0.84622744 -1.11263894  0.70887697 -1.48845508]
 [-1.28327466  0.62388402 -3.09730525 -1.22184296]
 [ 0.92318246 -0.44147661 -0.571271   -0.69638513]
 [-0.48188231 -0.4448002   0.45485325  1.51766834]
 [ 0.32058434 -1.85472708  1.91265706 -0.98197215]
 [ 0.4464898  -0.16721712 -1.62228351 -0.57061811]
 [-0.77479264 -1.23358084 -1.4253706   0.91321623]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [113]:
arr=np.linspace(1,14,15).reshape(5,3)
print(arr)
np.shape(arr)

[[ 1.          1.92857143  2.85714286]
 [ 3.78571429  4.71428571  5.64285714]
 [ 6.57142857  7.5         8.42857143]
 [ 9.35714286 10.28571429 11.21428571]
 [12.14285714 13.07142857 14.        ]]


(5, 3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [2]:
arr=np.linspace(1,15,16).reshape(2,2,4)
print(arr)
print(np.shape(arr))

[[[ 1.          1.93333333  2.86666667  3.8       ]
  [ 4.73333333  5.66666667  6.6         7.53333333]]

 [[ 8.46666667  9.4        10.33333333 11.26666667]
  [12.2        13.13333333 14.06666667 15.        ]]]
(2, 2, 4)


33. Swap axes of the array you created in Question 32

In [3]:
arr1=arr.swapaxes(1,2)
arr1

array([[[ 1.        ,  4.73333333],
        [ 1.93333333,  5.66666667],
        [ 2.86666667,  6.6       ],
        [ 3.8       ,  7.53333333]],

       [[ 8.46666667, 12.2       ],
        [ 9.4       , 13.13333333],
        [10.33333333, 14.06666667],
        [11.26666667, 15.        ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [10]:
arr=np.arange(10)
print(arr)
arr1=np.sqrt(arr)
print(arr1)
arr1[arr1<0.5]=0
arr1

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [14]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
print("Array 1\n",arr1)
print("\nArray 2\n",arr2)
arr=np.maximum(arr1,arr2)
print("\nMaximum Array Between Arrar1 and Array2\n",arr)

Array 1
 [-1.48921564  0.26813385  0.95581502 -0.09815008 -1.55313878 -2.08268604
 -0.92528289  1.33356719 -0.47350856  1.80667981 -1.23917493  1.26729442]

Array 2
 [ 0.22847357  0.2427528  -0.54028436 -0.3552852  -1.70041704 -0.66878507
  2.27706264 -1.11266034 -0.45254472  1.22307933 -0.32563315 -0.39613765]

Maximum Array Between Arrar1 and Array2
 [ 0.22847357  0.26813385  0.95581502 -0.09815008 -1.55313878 -0.66878507
  2.27706264  1.33356719 -0.45254472  1.80667981 -0.32563315  1.26729442]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [16]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arr=np.unique(names)
arr

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [18]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([5, 6, 7, 8, 9])
arr=np.setdiff1d(a, b)
arr

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print("Samlpe Array\n",sampleArray)
print("\nNew Column\n",newColumn)
del_arr=np.delete(sampleArray,1,1)
print("\nDeteted Array\n",del_arr)
col1=del_arr[0:3,0:1].reshape(1,3)
col2=del_arr[0:3,1:2].reshape(1,3)
col3=np.dstack((col1, newColumn))
arr=np.dstack((col3, col2))
print("\nReplaces Column Array\n",arr)

Samlpe Array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

New Column
 [[10 10 10]]

Deteted Array
 [[34 73]
 [82 12]
 [53 66]]

Replaces Column Array
 [[[34 10 73]
  [82 10 12]
  [53 10 66]]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [66]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product=np.dot(x,y)
print("Dot Product of Matrix\n",dot_product)

Dot Product of Matrix
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [70]:
arr=np.arange(20)
print("Array\n",arr)
arr1=arr.cumsum()
print("\nCumulative Sum\n",arr1)

Array
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Cumulative Sum
 [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
