# Name : Muhammad Usman Khan

# Roll No. : PIAIC79201

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
import numpy as np
arr=np.arange(10)
print("1D Array: ",arr,"\n")
print("Array Dimension: ",arr.ndim,"\n")
arr1=arr.reshape(2,5)
print("2D Array: \n",arr1)
print("Array Dimension: ",arr1.ndim)

1D Array:  [0 1 2 3 4 5 6 7 8 9] 

Array Dimension:  1 

2D Array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array Dimension:  2


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
import numpy as np
arr1=np.arange(10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
stacking=np.vstack((arr1,arr2))
print("Two Vertically Stack Arrays: \n")
stacking.astype("int32")

Two Vertically Stack Arrays: 



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
stacking=np.hstack((arr1,arr2))
print("Two Horizontically Stack Array :\n")
stacking.astype("int32")

Two Horizontically Stack Array :



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [22]:
arr=np.arange(10).reshape(5,2)
print("Original Array : \n")
print(arr)
arr1=np.ravel(arr)
print("\n1D Array: \n")
arr1

Original Array : 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

1D Array: 



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [27]:
arr=np.arange(15).reshape(3,5,1)
print("Original Array :\n")
print(arr)
arr1=np.ravel(arr)
print("\nOne Dimensional Array: \n")
arr1

Original Array :

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]

One Dimensional Array: 



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [29]:
arr=np.arange(15)
print("One Dinansional Array :\n")
print(arr)
arr1=arr.reshape(5,3)
print("\nHigher Dimensional Array :\n")
arr1

One Dinansional Array :

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Higher Dimensional Array :



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [32]:
arr=np.arange(25).reshape(5,5)
print("Original Array :\n")
print(arr)
arr1=np.sqrt(arr)
print("\nSquare Root of an Array :\n")
print(arr1)

Original Array :

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Square Root of an Array :

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]
 [4.47213595 4.58257569 4.69041576 4.79583152 4.89897949]]


## Question:8

### Create 5x6 an array and find the mean?

In [36]:
arr=np.arange(30).reshape(5,6)
print("Original Array :\n")
print(arr)
arr1=np.mean(arr)
print("\nMean of an Array :\n")
print(arr1)

Original Array :

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Mean of an Array :

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [42]:
arr1=np.std(arr)
print("Standard Deviation of an Array: \n")
print(arr1)

Standard Deviation of an Array: 

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [44]:
arr1=np.median(arr)
print("Median of an Array :\n")
print(arr1)

Median of an Array :

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [45]:
print("Original Array :\n")
print(arr)
arr1=arr.T
print("\nTranspose of an Array :\n")
print(arr1)

Original Array :

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Transpose of an Array :

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [52]:
arr=np.arange(16).reshape(4,4)
print("Original Array :\n")
print(arr)
arr1=np.trace(arr)
print("\nSum of Diahonal Elements\n")
print(arr1)

Original Array :

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of Diahonal Elements

30


## Question:13

### Find the determinant of the previous array in Q12?

In [59]:
print("Original Array :\n")
print(arr)
arr1=np.linalg.det(arr)
print("\nDeterminant of an Array :\n")
print(arr1)

Original Array :

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Determinant of an Array :

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [61]:
arr=np.arange(10)
print("Original Array :\n")
print(arr)
arr1=np.percentile(arr,5)
arr2=np.percentile(arr,95)
print("\n5th Percntile of an Array :\n",arr1)
print("\n95th Percntile of an Array :\n",arr2)

Original Array :

[0 1 2 3 4 5 6 7 8 9]

5th Percntile of an Array :
 0.45

95th Percntile of an Array :
 8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [81]:
arr1=np.zeros(5)
arr2=np.arange(5)
arr3=np.empty((5))
arr3[:]=np.NaN
print(arr1)
print(arr2)
print(arr3)
print("\nIf any True Retuns then it will be a Null Array\n")
print(np.isnan(arr1))
print(np.isnan(arr2))
print(np.isnan(arr3))

[0. 0. 0. 0. 0.]
[0 1 2 3 4]
[nan nan nan nan nan]

If any True Retuns then it will be a Null Array

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
